FROM alpine

# https://www.youtube.com/watch?v=hnxI-K10auY
# MAINTAINER <name> is deprecated

MAINTAINER Vijay Konduru "konduruvijaykumar@gmail.com"

CMD ["echo", "Hello, Welcome to docker from alpine linux!"]
